### PR TITLE
Add # of sessions to grab on /lovetap

### LINKED ISSUE #4: Make /lovetap less spammy
Compact sessions so I dont have to receive 100+ messages when using it through Kira

### PR DESCRIPTION
**Pull request by Diet-Cola**
Closes #4

Defaults to 25, on test

### CODE REVIEW

**Comment by Diet-Cola** [comment]
Need to do one more thing on this and will be ready

**Comment by wingzero54** [comment]
I think I would like it to default to all sessions, there are times when it's useful to see the full information and you have no way of knowing how many sessions there are up front

**Comment by wingzero54** [comment]
I'll accept this as soon as the default lovetap is all sessions, eagerly awaiting :)

**Comment by Diet-Cola** [comment]
Sorry been busy, will try sort asap

**Pull request merged**
